### ISSUE TITLE
Which is better? WebSockets or Telnet?

### ISSUE THREAD

**Issue by karoria** [grblHAL/Plugin_networking#1]
Hi @terjeio,

I want to make my own communication interface for grblHAL with Teensy4.1. I don't want to use USB serial to take advantage of robust ethernet connection. Now the question is should I use Telnet or WS? I am pretty sure, I can code my interface both ways but I am unclear about any disadvantage of using WS. I want to use Raspberry Pi 4 to communicate with controller. I will make RPi4 an http server, so that I can access my interface through any LAN connected device. I have 2 options:

1. Making RPi4 an http server with telnet communication to controller
2. Making Teensy 4.1 a WS server and use client side code in each LAN connected device including RPi4

I am not sure which way is better for me. Your guidance will be appreciated.

**Comment by terjeio** [comment]
Telnet is perhaps better for you as it is far simpler to code for, open a socket an you are ready to communicate. But if the code connecting to the websocket is running in a browser then [a websocket connection](https://github.com/grblHAL/Plugin_networking#simple-websocket-test-app) will be easier?

Be aware that grblHAL now has [webserver](https://github.com/grblHAL/Plugin_networking#protocols-supported) (http) support.  The [WebUI plugin](https://github.com/grblHAL/Plugin_WebUI) uses it for the [ESP32-WEBUI](https://github.com/luc-github/ESP3D-webui).

**Comment by karoria** [comment]
Yes, the UI will run in a browser. Basically it is a NodeJs project, but still telnet is easier to code than WS as I feel. Now the game changer is http webserver that I was not knowing. How much memory I get on teensy4.1 to write http webserver? I know Luc's webUI, but mine will be a little resource demanding. Thanks for your time.

**Comment by karoria** [comment]
OK. I can see the instructions in WebUI plugin to copy the www plugin to SD card. That means the http webserver is hosted from memory card. It should also mean it doesn't have controller specific storage limitations as it uses SD memory. I will have to check how it performs if that is the case.

**Comment by terjeio** [comment]
> I will have to check how it performs if that is the case.

It is the case, and loading _and_ starting the 156K (compressed) application happens in the blink of an eye (less than a second).

![image](https://user-images.githubusercontent.com/20260062/134810525-a50a2682-75f4-4957-83fa-f356ede69f82.png)

**Comment by karoria** [comment]
Thanks @terjeio, I am inclined to use http server through teensy. I can't find the folder hierarchy wiki after this project is re-organized to use sub-modules. I hope only "core" and "driver" repos to be cloned dependencies are taken care automatically. If so, should "core" project be inside "driver" project?

**Comment by karoria** [comment]
I am using PIO.

**Comment by terjeio** [comment]
Download info [here](https://github.com/grblHAL/core/wiki/Compiling-GrblHAL).

**Comment by karoria** [comment]
Thanks a lot.
